name: Netlify -> Algolia Crawler
on:
  push:
    branches: [ main ]
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Sleep for 30s
        run: sleep 30
      - name: Netlify-PR => Algolia crawler creation and recrawl on preview (Pull Request)
        if: github.ref != 'refs/heads/main'
        uses: ./
        id: crawler_pr
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1'
          crawler-name: netlify-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://deploy-preview-${{ github.event.pull_request.number }}--algolia-ga-actions-netlify.netlify.app/'
          override-config: true
      - name: Netlify-MAIN => Algolia crawler creation and recrawl (Push on Main branch)
        if: github.ref == 'refs/heads/main'
        uses: ./
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler.algolia.com/api/1'
          crawler-name: netlify-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://algolia-ga-actions-netlify.netlify.app/'
          override-config: true

