name: Vercel automatic reindexing with Algolia Crawler on push on Main branch
on:
  push:
    branches: [ main ]

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: algolia/algoliasearch-crawler-github-actions 
          ref: v0.4.2
      - name: Vercel-MAIN => Algolia crawler creation and reindex on preview (Push on Main branch)
        uses: ./
        id: crawler_push
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1/'
          crawler-name: vercel-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://algoliasearch-crawler-github-actions.vercel.app'
