name: Vercel -> Algolia Crawler (PR)
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  algolia_reindex:
    name: Algolia Reindex
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 1 
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: algolia/algoliasearch-crawler-github-actions 
          ref: v0.4.2
      - name: Vercel-PR => Algolia crawler creation and reindex on preview (Pull Request)
        uses: ./
        id: crawler_pr
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          crawler-api-base-url: 'https://crawler-dev.algolia.com/api/1/'
          crawler-name: vercel-github-actions-test-${{ github.ref }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: ${{ steps.deployment.outputs.deployment }}
